updated to using php74.

diff --git a/overlay/usr/local/bin/fusionpbxset b/overlay/usr/local/bin/fusionpbxset
--- a/overlay/usr/local/bin/fusionpbxset
+++ b/overlay/usr/local/bin/fusionpbxset
@@ -2,28 +2,28 @@
 
 set_sslkey()
 {
-  shift
-  key=$@
-  if [ $? -eq 0 ] && [ "$key" != "" ] ; then
-    echo "Changing /usr/local/etc/nginx/server.key..."
-    echo "$key" > /usr/local/etc/nginx/server.key
-  else
-    echo "Error when updateing /usr/local/etc/nginx/server.key">2 ; exit 1
-  fi
-  exit 0
+	shift
+	key=$@
+	if [ $? -eq 0 ] && [ "$key" != "" ] ; then
+		echo "Changing /usr/local/etc/nginx/server.key..."
+		echo "$key" > /usr/local/etc/nginx/server.key
+	else
+		echo "Error when updateing /usr/local/etc/nginx/server.key">2 ; exit 1
+	fi
+	exit 0
 }
 
 set_sslcert()
 {
-  shift
-  cert=$@
-  if [ $? -eq 0 ] && [ "$cert" != "" ] ; then
-    echo "Changing /usr/local/etc/nginx/server.crt..."
-    echo "$cert" > /usr/local/etc/nginx/server.crt
-  else
-    echo "Error when updateing /usr/local/etc/nginx/server.crt">2 ; exit 1
-  fi
-  exit 0
+	shift
+	cert=$@
+	if [ $? -eq 0 ] && [ "$cert" != "" ] ; then
+		echo "Changing /usr/local/etc/nginx/server.crt..."
+		echo "$cert" > /usr/local/etc/nginx/server.crt
+	else
+		echo "Error when updateing /usr/local/etc/nginx/server.crt">2 ; exit 1
+	fi
+	exit 0
 }
 
 # Stub for something which sets quasselsettings
